definitions:
  controller.humanResponse:
    properties:
      message:
        example: DNA_HUMAN
        type: string
    type: object
  controller.inputDNA:
    properties:
      dna:
        example:
        - ATACA
        - AGGCT
        - AGCTC
        - ACCAA
        - CCATG
        items:
          type: string
        type: array
    type: object
  controller.inputErrorResponse:
    properties:
      message:
        example: STRAND_LENGTH_INVALID
        type: string
    type: object
  controller.mutantResponse:
    properties:
      message:
        example: DNA_MUTANT
        type: string
    type: object
  controller.serverErrorResponse:
    properties:
      message:
        example: INTERNAL_SERVER_ERROR
        type: string
    type: object
  model.HealthCheckResponse:
    properties:
      status:
        type: string
    type: object
  model.Stats:
    properties:
      count_human_dna:
        type: integer
      count_mutant_dna:
        type: integer
      ratio:
        type: number
    type: object
info:
  contact: {}
paths:
  /heatlhcheck:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Check the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: Status OK
          schema:
            $ref: '#/definitions/model.HealthCheckResponse'
      summary: Healthcheck
      tags:
      - Mutant
  /mutant:
    post:
      description: Validates whether the DNA strand is human or mutant
      parameters:
      - description: DNA strand
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controller.inputDNA'
      produces:
      - application/json
      responses:
        "200":
          description: DNA is mutant
          schema:
            $ref: '#/definitions/controller.mutantResponse'
        "400":
          description: Input error
          schema:
            $ref: '#/definitions/controller.inputErrorResponse'
        "403":
          description: DNA is human
          schema:
            $ref: '#/definitions/controller.humanResponse'
        "500":
          description: Errors found
          schema:
            $ref: '#/definitions/controller.serverErrorResponse'
      summary: DNA strand is human or mutant
      tags:
      - Mutant
  /stats:
    get:
      description: Obtains the DNA statistics of mutants vs. humans.
      produces:
      - application/json
      responses:
        "200":
          description: Stats for DNA strand
          schema:
            $ref: '#/definitions/model.Stats'
        "500":
          description: Errors found
          schema:
            $ref: '#/definitions/controller.serverErrorResponse'
      summary: Stats for DNA mutants vs. humans
      tags:
      - Mutant
swagger: "2.0"
